version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samcogntio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j05ohfod6sge"
s3_prefix = "samcogntio"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
